language: cpp

compiler:
  - gcc

# see: https://gist.github.com/Kakadu/7dc6f7c9f8760f7fbace

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo /bin/sh -c "echo 'force-confold' >>/etc/dpkg/dpkg.cfg"
  - sudo apt-get update
  - sudo apt-get remove -y 'postgresql*'
  - DEBIAN_FRONTEND=noninteractive sudo -E apt-get upgrade -y

install:
  - DEBIAN_FRONTEND=noninteractive sudo -E apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps xterm libqt5svg5-dev qttools5-dev qtscript5-dev qtdeclarative5-folderlistmodel-plugin qtdeclarative5-controls-plugin libqt5xmlpatterns5-dev qtxmlpatterns5-dev-tools -y
  - DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y libfuse-dev
  - sudo sed -i s/explicit// /usr/include/qt5/QtCore/qcommandlineoption.h

script:
  - qmake -qt=qt5
  - make
