install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qttools5-dev-tools libfuse-dev
  - sudo sed -i s/explicit// /usr/include/qt5/QtCore/qcommandlineoption.h

script:
  - qmake -qt=qt5
  - make
